### ISSUE TITLE
A2.6: Elaborar informe history of project

### ISSUE THREAD

**Issue by artrodase** [gii-is-psg2/psg2-2122-g4-43#13]
Elaborar en grupo un informe técnico (en español) que describa la historia del proyecto (history of the project) después de terminar con las tareas anteriores. Este documento debe incluir un diagrama que muestre una línea de tiempo de los commits en el repositorio, identificando los conflictos que surgieron, si los hubo, y describiendo cómo el grupo resolvió esos conflictos.

**Comment by andrsdt** [comment]
Revisado y todo correcto. He hecho pequeñas modificaciones en el formato (texto justificado) y he añadido un poco más de contenido a la conclusión
