### ISSUE TITLE
A2.9: Preparar el código fuente para el despliegue

### ISSUE THREAD

**Issue by artrodase** [gii-is-psg2/psg2-2122-g4-43#25]
Antes del despliegue, todos los miembros del grupo deben reunirse para eliminar cualquier error y advertencia que esté presente en todos los archivos del código fuente desarrollado.

**Comment by jonatep** [comment]
Todo bien y en orden :)

**Comment by jonatep** [comment]
Después de hablarlo con los demás compañeros, vamos a mirar en detalle el aspecto de los caracteres "Ñ" en la página

**Comment by artrodase** [comment]
Es posible que al utilizar vosotros Linux os ha ido bien, a los demás que utilizamos Windows no nos funciona como a vosotros

**Comment by artrodase** [comment]
Acabo de ver que no se puede eliminar visitas
