### ISSUE TITLE
Extra criteria: extender el informe A2.6

### ISSUE THREAD

**Issue by artrodase** [gii-is-psg2/psg2-2122-g4-43#29]
Extender el informe A2.6 incluyendo el historial de cambios realizados para A2.8 y A2.9. El documento también debe incluir una reflexión sobre los beneficios y desventajas de usar la estrategia de branching

**Comment by jonatep** [comment]
Terminada la ampliación del documento

**Comment by artrodase** [comment]
Todo bien en general. Yo consideraría ampliar un poco más sobre las causas de la creación de la rama hotfix.

**Comment by jonatep** [comment]
Okey, ya lo amplié más

**Comment by artrodase** [comment]
Perfecto, está bien justificado.
