### ISSUE TITLE
A3.E.3: Crear apéndice en el A3.6 sobre cómo usar GitFlow sobre las épicas (elección y motivo)

### ISSUE THREAD

**Issue by andrsdt** [gii-is-psg2/psg2-2122-g4-43#39]
As a group, create an appendix in the technical report created as a result of A3.6 to describe the policy used to integrate the use of epics into the GitFlow branching methodology. Among the options available for such integration are:

* Use branches for epics in the same way as they were used for any other issue/task.
* Use branches only for the concrete issues/tasks belonging to epics, but not the epic itself.
* Apply the approach proposed here

**Comment by andrsdt** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-43-6233043e186c100019aa5edf/issues/gii-is-psg2/psg2-2122-g4-43/39?planning-poker) with ZenHub @jonatep @joscacgom @meriglmar @davsabtro

**Comment by jonatep** [comment]
Todo bien y claro por mi parte :)

**Comment by joscacgom** [comment]
Todo claro y correcto !!

**Comment by andrsdt** [comment]
Todo claro, entiendo cómo hay que aplicar la metodología

**Comment by artrodase** [comment]
He revisado el documento y me uno a las opiniones de mis compañeros. Buen trabajo.

**Comment by andrsdt** [comment]
Falta la revisión de @davsabtro para poder dar la tarea por concluida

**Comment by davsabtro** [comment]
Todo perfecto

**Comment by andrsdt** [comment]
A la hora de redactar el documento no tuvimos en cuenta los siguientes matices:
* La persona que revisa una tarea puede arreglar los problemas de código si son menores o tiene que hacerlo necesariamente el desarrollador?
* La persona que hace merge de la última rama de la subtarea épica tiene que resolver los conflictos que se planteen?
* La persona que hace merge de la rama épica a la rama develop tiene que resolver los conflictos que se planteen?

Es por eso que vamos a mover la tarea a "In Progress" para terminar de aclarar esto y que el grupo pueda tener una idea más acertada y sencilla

**Comment by artrodase** [comment]
He revisado el documento actualizado y considero que aún hay algunas cosas que mejorar. Dejo en los comentarios en el propio documento los puntos que considero que deberíamos mejorar.

**Comment by andrsdt** [comment]
Tras la reunión que de coordinación que ha mantenido todo el grupo sobre el documento, damos la tarea por concluída.
