### ISSUE TITLE
A3.5 a): Crear la funcionalidad de causas

### ISSUE THREAD

**Issue by andrsdt** [gii-is-psg2/psg2-2122-g4-43#41]

**Comment by andrsdt** [comment]
@davsabtro @jonatep @joscacgom Ya hemos terminado esta épica 🥳, como **equipo épico** de esta tarea, es recomendable que revisemos que todo funciona bien como un conjunto. Yo por mi parte no he detectado problemas. Cuando me déis el visto bueno, abro la pull request

**Comment by jonatep** [comment]
Por mi parte tampoco he visto problema alguno, todo bien :)

**Comment by joscacgom** [comment]
Todo bien por mi parte
