### ISSUE TITLE
A3.5 c): Crear la funcionalidad de adopciones

### ISSUE THREAD

**Issue by andrsdt** [gii-is-psg2/psg2-2122-g4-43#46]

**Comment by artrodase** [comment]
He revisado el funcionamiento de la épica. He probado distintos escenarios y confirmo que todo funciona según lo esperado. Solo un detalle: ¿tal vez faltaría el botón de rechazar la solicitud de adopción? Aunque he visto que al aprobar una se rechazan otras automáticamente.
