### ISSUE TITLE
A3.E.1: Extender technical reports de A3.6 y A3.7 con los datos del S2 y discusión de diferencias

### ISSUE THREAD

**Issue by andrsdt** [gii-is-psg2/psg2-2122-g4-43#60]

**Comment by jonatep** [comment]
Ya están redactadas las diferencias junto con las discusiones de las mismas en ambos documentos :)

**Comment by andrsdt** [comment]
En general todo está bastante bien! He hecho algunos cambios menores (especificar que usamos SonarQube, de código libre, y no la plataforma de pago SonarCloud; usar la palabra "métrica" en lugar de "medición" y pequeños cambios gramaticales). Buen trabajo 🥳
