### ISSUE TITLE
A2.5 -b: Cambiar información del proyecto en el pom

### ISSUE THREAD

**Issue by artrodase** [gii-is-psg2/psg2-2122-g4-43#8]
Cambie la información del proyecto en pom.xml según los siguientes atributos (donde
GX-XY es su ID de grupo):
a) groupId = es.us.psg2
b) artifactId = spring-petclinic.psg2.2122-GX-XY
c) version = 1.0.0
d) name = PSG2-2122-GX-XY Petclinic

**Comment by joscacgom** [comment]
Todo correcto
